// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetRepositoryTagsParams creates a new GetRepositoryTagsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetRepositoryTagsParams() *GetRepositoryTagsParams {
	return &GetRepositoryTagsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetRepositoryTagsParamsWithTimeout creates a new GetRepositoryTagsParams object
// with the ability to set a timeout on a request.
func NewGetRepositoryTagsParamsWithTimeout(timeout time.Duration) *GetRepositoryTagsParams {
	return &GetRepositoryTagsParams{
		timeout: timeout,
	}
}

// NewGetRepositoryTagsParamsWithContext creates a new GetRepositoryTagsParams object
// with the ability to set a context for a request.
func NewGetRepositoryTagsParamsWithContext(ctx context.Context) *GetRepositoryTagsParams {
	return &GetRepositoryTagsParams{
		Context: ctx,
	}
}

// NewGetRepositoryTagsParamsWithHTTPClient creates a new GetRepositoryTagsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetRepositoryTagsParamsWithHTTPClient(client *http.Client) *GetRepositoryTagsParams {
	return &GetRepositoryTagsParams{
		HTTPClient: client,
	}
}

/* GetRepositoryTagsParams contains all the parameters to send to the API endpoint
   for the get users operation.

   Typically these are written to a http.Request.
*/
type GetRepositoryTagsParams struct {

	/* RepoName

	   repo name
	*/
	RepoName *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get users params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRepositoryTagsParams) WithDefaults() *GetRepositoryTagsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get users params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRepositoryTagsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get users params
func (o *GetRepositoryTagsParams) WithTimeout(timeout time.Duration) *GetRepositoryTagsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get users params
func (o *GetRepositoryTagsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get users params
func (o *GetRepositoryTagsParams) WithContext(ctx context.Context) *GetRepositoryTagsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get users params
func (o *GetRepositoryTagsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get users params
func (o *GetRepositoryTagsParams) WithHTTPClient(client *http.Client) *GetRepositoryTagsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get users params
func (o *GetRepositoryTagsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEmail adds the email to the get users params
func (o *GetRepositoryTagsParams) WithRepoName(reponame *string) *GetRepositoryTagsParams {
	o.SetRepoName(reponame)
	return o
}

// SetEmail adds the email to the get users params
func (o *GetRepositoryTagsParams) SetRepoName(reponame *string) {
	o.RepoName = reponame
}

// WriteToRequest writes these params to a swagger request
func (o *GetRepositoryTagsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.RepoName != nil {

		// query param email
		var qrRepoName string

		if o.RepoName != nil {
			qrRepoName = *o.RepoName
		}
		qRepoName := qrRepoName
		if qRepoName != "" {

			if err := r.SetPathParam("repo_name", qRepoName); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
